### ISSUE TITLE
Incorrent documentation for out_http

### ISSUE THREAD

**Issue by Horkyze** [fluent/fluentd-docs-gitbook#103]
https://docs.fluentd.org/output/http states:
```
<match pattern>
  @type http

  endpoint http://logserver.com:9000/api
  open_timeout 2
```

where in fact `endpoint_url` is the corrent parameter.

**Comment by Horkyze** [comment]
```
fluentd_1         | 2019-09-23 11:46:33 +0000 [error]: config error in:
fluentd_1         | <match **>
fluentd_1         |   @type http
fluentd_1         |   endpoint http://journal-module:1514/
fluentd_1         |   content_type json
fluentd_1         |   <format>
fluentd_1         |     @type json
fluentd_1         |   </format>
fluentd_1         | </match>
fluentd_1         |
fluentd_1         | 2019-09-23 11:46:33 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="'endpoint_url' parameter is required"
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/config/section.rb:163:in `block in generate'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/config/section.rb:136:in `each_pair'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/config/section.rb:136:in `generate'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/configurable.rb:94:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/plugin/base.rb:63:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/plugin_id.rb:39:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/log.rb:587:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/plugin/output.rb:247:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/plugin_helper/formatter.rb:83:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluent-plugin-out-http-1.3.1/lib/fluent/plugin/out_http.rb:82:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/plugin.rb:164:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/agent.rb:130:in `add_match'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/agent.rb:72:in `block in configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/agent.rb:64:in `each'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/agent.rb:64:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/label.rb:31:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/root_agent.rb:147:in `block in configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/root_agent.rb:147:in `each'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/root_agent.rb:147:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/engine.rb:131:in `configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/engine.rb:96:in `run_configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/supervisor.rb:804:in `run_configure'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/supervisor.rb:581:in `dry_run'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/supervisor.rb:599:in `supervise'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/supervisor.rb:504:in `run_supervisor'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/lib/fluent/command/fluentd.rb:314:in `<top (required)>'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.7.2/bin/fluentd:8:in `<top (required)>'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/bin/fluentd:23:in `load'
fluentd_1         |   2019-09-23 11:46:33 +0000 [debug]: /usr/local/bundle/bin/fluentd:23:in `<main>'
```

**Comment by Horkyze** [comment]
Nevermind, it was my bad, I was using old our_http plugin (installed via gem)
