### ISSUE TITLE
Parser plugin multiline doesn't work as it appears in docs

### ISSUE THREAD

**Issue by satrushn** [fluent/fluentd-docs-gitbook#338]
Parser plugin multiline doesn't work as it appears in docs or there is a misunderstanding.
I tried to use parser multiline in section <filter> as it appears in docs : https://docs.fluentd.org/parser/multiline
I need to collect several lines in one message.

Example of log:

[DockerLogGenerator] Multiline: 2021-07-01 12:29:42.862326529 +0000 UTC m=+107095.440406775
This is the second line
This is the third line

I expect that this log will be parsed as something like this:

record:
{
  "message":"[DockerLogGenerator] Multiline: 2021-07-01 12:29:42.862326529 +0000 UTC m=+107095.440406775\n This is the second line\n This is the third line
}

But it doesn't appears.

Example of my config:
...
<filter **>
  @type parser
  key_name log
  reserve_data true
  <parse>
    @type multiline
    format_firstline /^.*Multiline/
    format1 /^(?<message>.*)/
  </parse>
</filter>
...

Would you make clear in docs, how to collect multiline logs correctly in this case, please?
Thanks.

**Comment by kenhys** [comment]
I guess that `<parse>` in `<source>` may be what you want to do.

Here is the sample.
```
<source>
  @type tail
  path logs.txt
  tag test
  read_from_head true
  <parse>
     @type multiline
     format_firstline /\[/
     format1 /^(?<message>.*)/
  </parse>
</source>

<match test>
  @type stdout
</match>
```

OUTPUT:

```
2021-07-02 11:27:24 +0900 [info]: #0 following tail of logs.txt
2021-07-02 11:27:24.876553899 +0900 test: {"message":"[DockerLogGenerator] Multiline: 2021-07-01 12:29:42.862326529 +0000 UTC m=+107095.440406775\r\nThis is the second line\r\nThis is the third line"}
2021-07-02 11:27:24 +0900 [info]: #0 fluentd worker is now running worker=0
```

**Comment by satrushn** [comment]
Thank you for your answer.
I try to use Fluentd as Fluentd-operator, there is no way to change something in <source> that's why I want to use parser in filter.
Is there another method to solve the problem?

**Comment by kenhys** [comment]
> I try to use Fluentd as Fluentd-operator, there is no way to change something in "source" that's why I want to use parser in filter.
Is there another method to solve the problem?

I do not understand well, but https://github.com/fluent-plugins-nursery/fluent-plugin-concat may help you.

**Comment by fireinmysou1** [comment]
Hi there!
I have the same issue.

My logs looks like this:

`2023-02-21 15:51:23.668 [main] INFO org.flywaydb.core.internal.license.VersionPrinter -
Feb 21, 2023 3:51:33 PM org.apache.tomcat.jdbc.pool.ConnectionPool init
SEVERE: Unable to create initial connections of pool.
org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
        at org.postgresql.Driver.makeConnection(Driver.java:402)
`
and so on


My fluentd.conf:

`    <filter dev.thing>
      @type parser
      key_name log
      reserve_time true
      <parse>
        @type multiline
        format_firstline /\d{4}-\d{1,2}-\d{1,2}/
        format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{1,3}) \[(?<thread>.*?)\] (?<level>.*?) (?<message>(.|\n)*)/
      </parse>
    </filter>

    <match dev.thing>
      @type copy
      <store>
        @type opensearch
        host opensearch.example.com
        port 443
        scheme https
        logstash_format true
        logstash_prefix dev.thing
        type_name access_log
        <buffer>
          flush_interval 10s
        </buffer>
        user user
        password 123123123
      </store>
      <store>
        @type stdout
      </store>
    </match>`

I tried example from [here ](https://docs.fluentd.org/parser/multiline) but it doesn`t work too.
And only one thing that see in fluentd logs:

`2023-02-21 13:20:27.000000000 +0000 dev.thing: {"thread":"main","level":"INFO","message":"org.flywaydb.core.internal.license.VersionPrinter - "}
2023-02-21 13:20:37 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not matched with data 'Feb 21, 2023 4:20:37 PM org.apache.tomcat.jdbc.pool.ConnectionPool init'" location=nil tag="dev.thing" time=1676985637 record={"source"=>"stderr", "log"=>"Feb 21, 2023 4:20:37 PM org.apache.tomcat.jdbc.pool.ConnectionPool init", "container_id"=>"9fba52c708e526f36c1a99710b72ae33b38d984dd882a3dce9925f63b35b5add", "container_name"=>"/dev-thing", "env"=>"dev"}
2023-02-21 13:20:37 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::Parser::ParserError error="pattern not matched with data 'SEVERE: Unable to create initial connections of pool.'" location=nil tag="dev.thing" time=1676985637 record={"source"=>"stderr", "log"=>"SEVERE: Unable to create initial connections of pool.", "container_id"=>"9fba52c708e526f36c1a99710b72ae33b38d984dd882a3dce9925f63b35b5add", "container_name"=>"/dev-thing", "env"=>"dev"}
`

Can you tell me please how can I use    <parse> @type multiline for WHOLE trace from firstline to firstline.
Off docs for multiline simple doesnt help me.
So my point is documentation is not correct.
Thanks!

**Comment by joek-office** [comment]
Hello together,
have seen this old post and it looks like that i have the same or a near problem. Hope anyone can clarify the documentation or give a way to solve my problem.

What i want to do:
I have many different files with different log formats. For this i have written a new regex to use with multiline. The jumping point here is, that i have many one line logs and multiline logs. i want to solve this like in the documentation (Java Stacktrace Log
). The problem is, that in the environment comes for multiline log output the following error message:
`#0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log` 
and then follows the lines one by one from the log output.

```
'2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "[2023-07-10 14:04:31 +0200].535 35 WARNING [-] Invalid HTTP request received.\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "Traceback (most recent call last):\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "  File \"/var/lib/kolla/venv/lib64/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py\", line 129, in handle_events\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "    event = self.conn.next_event()\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "  File \"/var/lib/kolla/venv/lib64/python3.9/site-packages/h11/_connection.py\", line 443, in next_event\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "    exc._reraise_as_remote_protocol_error()\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "  File \"/var/lib/kolla/venv/lib64/python3.9/site-packages/h11/_util.py\", line 76, in _reraise_as_remote_protocol_error\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "    raise self\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "  File \"/var/lib/kolla/venv/lib64/python3.9/site-packages/h11/_connection.py\", line 425, in next_event\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "    event = self._extract_next_receive_event()\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "  File \"/var/lib/kolla/venv/lib64/python3.9/site-packages/h11/_connection.py\", line 367, in _extract_next_receive_event\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "    event = self._reader(self._receive_buffer)\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "  File \"/var/lib/kolla/venv/lib64/python3.9/site-packages/h11/_readers.py\", line 68, in maybe_read_from_IDLE_client\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "    raise LocalProtocolError(\"illegal request line\")\n"
2023-07-10 14:04:31 +0200 [warn]: #0 got incomplete line before first line from /var/log/kolla/skyline/skyline-error.log: "h11._util.RemoteProtocolError: illegal request line\n"'
```

My configuration is as follows:

```
\<source>
  \@ type tail
  path /var/log/kolla/*/*-access.log,/var/log/kolla/*/*-error.log,/var/log/kolla/*/*_access.log,/var/log/kolla/*/*_error.log
  pos_file /var/run/td-agent/kolla-openstack-wsgi.pos
  tag kolla.*
  enable_watch_timer false
  \<parse>
    \@ type multiline
    format_firstline /^([^\/\r\nA-Z]*?\[|\[?)(?<Timestamp>((\+)?((?<=[A-Za-z]{4})\d{2,6}|(?<![A-Za-z]{4})(\d{2,6}|\w{3}))(\/|-|:|\s|\.)?){3,7}(?=\d{4}\])\d{4})\]?/
    format1 /^([^\/\r\nA-Z]*?\[|\[?)(?<Timestamp>((\+)?((?<=[A-Za-z]{4})\d{2,6}|(?<![A-Za-z]{4})(\d{2,6}|\w{3}))(\/|-|:|\s|\.)?){3,7}(?=\d{4}\])\d{4})\]?(?<Payload>.*)/
  \</parse>
\</source>
```

I match the following log formats with this regex:

```
'10.1.101.12 - - [28/Jun/2023:08:11:12 +0200]
[Tue Jun 27 12:07:40.882366 2023]
[2023-06-28 08:36:26 +0200].455
2023/06/28 08:36:20
2023-06-27 09:49:10.619993'
the regex looks for pieces of the strings, not for the whole strings
piece: [prefix][infix][suffix] up to seven times
prefix: could be a + sign, not mandatory
infix: 2-6 digits or 3 word characters
suffix: one of /,-,:,. or space char
```

after the up to seven pieces it is possible to have a additional four digits if no characters are present

Can anyone help or advise why fluentd cant parse this log output as multiline and give the error message?

**Comment by Watson1978** [comment]
Thanks for the report, and sorry for the very long delay.

## Root cause

This is a documentation issue rather than a bug. The `multiline` parser plugin itself does not join multiple lines.

Looking at the source of v1.19.3, `Fluent::Plugin::MultilineParser#parse` only applies a regexp built from `formatN` (with `Regexp::MULTILINE`) to the text it is given. It never buffers events. What it exposes to the caller is just the helper methods `has_firstline?` and `firstline?`.

The actual line-joining logic lives in `in_tail`:

- `in_tail.rb` sets `@multiline_mode` when the `@type` of the `<parse>` section contains `multiline`, and then uses `parse_multilines` as its receive handler.
- `parse_multilines` calls `@parser.firstline?(line)` and keeps appending lines to a line buffer until the next first line is detected.

So the buffering exists only in `in_tail`. When you put `@type multiline` into `<filter parser>`, the filter receives events that have already been split into one line per event, and `filter_parser` simply calls `parse` on a single field value. There is no `ConfigError` and no warning in that path, which is why it silently produces a result different from what you expected.

## About the current wording in the docs

The article already carries a constraint notice, but it only talks about *input* plugins:

> Unlike other parser plugins, this plugin needs special code in input plugin e.g. handle `format_firstline`. So, currently, `in_tail` plugin works with `multiline` but other input plugins do not work with it.

This does not cover `<filter>`, so the limitation is not discoverable for your use case. That is the real gap here.

## What we will clarify

We are going to replace that sentence with an explicit notice along these lines:

```markdown
{% hint style='warning' %}
This parser plugin itself does not join multiple lines. The logic to buffer lines and detect the start of each record is implemented in `in_tail`.

* `<parse>` in `in_tail`: works as described in this article.
* `<filter parser>` and other plugins which receive already-split events: cannot join separate events into one record. It can only parse a value which already contains newline characters.

To concatenate multiple events into one record after the input stage, use [`fluent-plugin-concat`](https://github.com/fluent-plugins-nursery/fluent-plugin-concat).
{% endhint %}
```

Note that saying "multiline does not work in a filter" would be inaccurate: because the regexp is compiled in multiline mode, it can still match a field value that already contains newline characters (for example a whole block delivered in a single field). What is impossible is joining separate events.

## Workaround

If you cannot modify the `<source>` section (as in the fluentd-operator case), use [`fluent-plugin-concat`](https://github.com/fluent-plugins-nursery/fluent-plugin-concat), which is designed to concatenate multiple events into one record in the middle of the pipeline.

## Regarding the later comment about `got incomplete line before first line`

@joek-office That warning is emitted by `in_tail` when a line arrives before any line has matched `format_firstline`. It indicates that your `format_firstline` regexp does not match the beginning of your log records, which is a configuration issue distinct from the topic of this issue. Please open a new issue or a support question with a minimal reproducible configuration if it is still relevant.

I will send a pull request for the documentation update, and this issue will be closed automatically when it is merged.
