### ISSUE TITLE
Incorrect instructions to build a fluentd with elasticsearch-plugin for docker image

### ISSUE THREAD

**Issue by stiliajohny** [fluent/fluentd-docs-gitbook#387]
### Describe the bug

At the page `https://docs.fluentd.org/v/0.12/articles/docker-logging-efk-compose`
The instructions given on `https://docs.fluentd.org/v/0.12/articles/docker-logging-efk-compose#step-1-prepare-fluentd-image-with-your-config-+-plugin` are incorrect 

This has been tested on MacOS ( docker desktop ) and Archlinux ( docker runtime ) 

The current error if these instructions are used is 

<details>
  <summary>Click to expand for error log</summary>
```bash 
etching excon-0.90.0.gem
#<Thread:0x00007f19ec5734f8@/usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `initialize': Permission denied @ rb_sysopen - /usr/local/bundle/cache/excon-0.90.0.gem (Errno::EACCES)
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `open'
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `write_binary'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:305:in `cache_update_path'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
Fetching faraday-net_http-1.0.1.gem
#<Thread:0x00007f19ec573098@/usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `initialize': Permission denied @ rb_sysopen - /usr/local/bundle/cache/faraday-net_http-1.0.1.gem (Errno::EACCES)
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `open'
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `write_binary'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:305:in `cache_update_path'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
Fetching ruby2_keywords-0.0.5.gem
#<Thread:0x00007f19ec573200@/usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `initialize': Permission denied @ rb_sysopen - /usr/local/bundle/cache/ruby2_keywords-0.0.5.gem (Errno::EACCES)
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `open'
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `write_binary'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:305:in `cache_update_path'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
Fetching faraday-retry-1.0.3.gem
#<Thread:0x00007f19ec573688@/usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `initialize': Permission denied @ rb_sysopen - /usr/local/bundle/cache/faraday-retry-1.0.3.gem (Errno::EACCES)
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `open'
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `write_binary'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:305:in `cache_update_path'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
Fetching faraday-net_http_persistent-1.2.0.gem
#<Thread:0x00007f19ec573390@/usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `initialize': Permission denied @ rb_sysopen - /usr/local/bundle/cache/faraday-net_http_persistent-1.2.0.gem (Errno::EACCES)
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `open'
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `write_binary'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:305:in `cache_update_path'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
Fetching faraday-rack-1.0.0.gem
#<Thread:0x00007f19ec5739d0@/usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `initialize': Permission denied @ rb_sysopen - /usr/local/bundle/cache/faraday-rack-1.0.0.gem (Errno::EACCES)
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `open'
        from /usr/local/lib/ruby/2.6.0/rubygems.rb:876:in `write_binary'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:305:in `cache_update_path'
        from /usr/local/lib/ruby/2.6.0/rubygems/remote_fetcher.rb:158:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/source.rb:206:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/resolver/specification.rb:101:in `download'
        from /usr/local/lib/ruby/2.6.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/bundle/cache/faraday-rack-1.0.0.gem
```
</details>

### Link to the problematic documentation

https://docs.fluentd.org/v/0.12/articles/docker-logging-efk-compose#step-1-prepare-fluentd-image-with-your-config-+-plugin

### Expected explanation

Update the document, 
The most appropriate documentations I have found was under `https://hub.docker.com/r/fluent/fluentd/` on the section `3. Customize Dockerfile to install plugins (optional)` in particular `3.1 For current images` 

I would suggest either copy the context of one of the dockerfiles or point the user reading the initial docs to the dockerhub docs ( the first option is more optimal IMO) 

### Additional context

this document was reviewed d2 years ago, it is expected technology, dependencies and implementation to have change.

**Comment by cosmo0920** [comment]
Have you tested on v1 version of documentation instruction? Fluentd v0.12 is already EOL and not maintained.

**Comment by stiliajohny** [comment]
> Have you tested on v1 version of documentation instruction? Fluentd v0.12 is already EOL and not maintained.

Aw, that might be one of the reasons, 
After googling I didn't ended up on this link :) 

Might be worth having a banner or a suggestion to visit the latest docs 

Thanks so much for that !!

**Comment by stiliajohny** [comment]
@kenhys  
Closed as completed due to ??? MR addressing the issue ? 
TIA
